title: "Brian Stewart | The Codesmith"
author: "Brian C. Stewart"
description: >
  My passion is learning, envisioning, creating. Crafting software is simply an extension of my lifelong love of building and design: first in Legos, then in rockets, then in carpentry. Building well matters to me.

url: "http://thecodesmith.com"
source_url: "https://github.com/thecodesmith/thecodesmith.github.io"
permalink: /:year/:month/:day/:title/

email: brian@thecodesmith.com
linkedin_username:      thecodesmith
github_username:        thecodesmith
stackoverflow_username: thecodesmith
twitter_username:       thecodesmith_

title_image: images/brian_stewart.jpg

post_limit: 5

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
