title: The Codesmith's Journal
email: brian@thecodesmith.com
description: >
  This is the technical journal for the codesmith, Brian Stewart.
  Topics include software craftsmanship, clean code, domain-specific
  languages (DSLs) and human-friendly tools, among others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thecodesmith.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thecodesmith
github_username:  thecodesmith

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
